name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  publish-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - run: npx openapi-generate-html -i reference/openapi.yml
        