name: publish docs to pages

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed

jobs:
    publish-to-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-node@v6.4.0
              with:
                  node-version: 24

            - run: mkdir docs

            - run: npx openapi-generate-html -i reference/openapi.yml --ui swagger -o docs/docs.html

            - name: deploy to pages
              uses: rossjrw/pr-preview-action@v1
              with:
                source-dir: ./docs/
                qr-code: false
                wait-for-pages-deployment: true
